# Generated by Django 4.0.2 on 2022-05-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_film_table_alter_game_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('sys_user', models.CharField(max_length=255)),
                ('json_params', models.JSONField()),
            ],
        ),
    ]
