# Generated by Django 4.0.2 on 2022-05-23 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_add', models.DateField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.users')),
            ],
        ),
    ]
