# Generated by Django 4.0.2 on 2022-05-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_favoritefilm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritefilm',
            options={'managed': False},
        ),
    ]
