# Generated by Django 4.0.2 on 2022-05-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_favoritefilm_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favoritefilm',
            table='FaveFilms',
        ),
    ]
