# Generated by Django 4.0.2 on 2022-05-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_favoritefilm_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favoritefilm',
            table=None,
        ),
    ]
