# Generated by Django 4.0.2 on 2022-05-23 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0010_users_pic_users_user_profile'),
    ]

    operations = [
        # # migrations.AddField(
        # #     model_name='users',
        # #     name='pic',
        # #     field=models.TextField(default=None),
        # # ),
        # # migrations.AddField(
        # #     model_name='users',
        # #     name='user',
        # #     field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
