# Generated by Django 4.0.2 on 2022-05-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_profile_adress_profile_bio_profile_city_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Users',
        # ),
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False},
        ),
    ]
