# Generated by Django 4.0.2 on 2022-05-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_delete_users_comment_article_comment_author'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Users',
        # ),
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False},
        ),
    ]
