# Generated by Django 4.0.2 on 2022-05-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_delete_users_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritefilm',
            options={'managed': True},
        ),
    ]
