# Generated by Django 4.0.2 on 2022-05-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_alter_favoritefilm_dt_add_alter_favoritefilm_user_and_more'),
    ]

    # # operations = [
    # #     migrations.DeleteModel(
    # #         name='Users',
    # #     ),
    # ]
