# Generated by Django 4.0.2 on 2022-05-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_delete_users'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Users',
        # ),
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True},
        ),
    ]
