# Generated by Django 4.0.2 on 2022-06-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_alter_chatmessage_table_alter_updates_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='favoritefilm',
            name='dt_deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='favoritefilm',
            name='is_deleted',
            field=models.SmallIntegerField(default=0),
        ),
    ]
