# Generated by Django 4.0.2 on 2022-06-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_delete_users_favoritefilm_dt_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True},
        ),
    ]
