# Generated by Django 4.0.2 on 2022-06-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_comment_article_comment_dt_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dt_deleted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='favoritefilm',
            name='dt_deleted',
        ),
        migrations.RemoveField(
            model_name='favoritefilm',
            name='is_deleted',
        )
    ]
